Work around GCC 6 this-capture in generic lambda
Summary:
GCC prior to 7.1 fails to build `OomKiller.cpp` with:

  ../OomKiller.cpp: In instantiation of ‘Oomd::OomKiller::removeBlacklisted(std::vector<std::pair<std::__cxx11::basic_string<char>, Oomd::CgroupContext> >&)::<lambda(const auto:27&)> [with auto:27 = std::pair<std::__cxx11::basic_string<char>, Oomd::CgroupContext>]’:
  /usr/include/c++/6/bits/predefined_ops.h:241:11:   required from ‘bool __gnu_cxx::__ops::_Iter_pred<_Predicate>::operator()(_Iterator) [with _Iterator = __gnu_cxx::__normal_iterator<std::pair<std::__cxx11::basic_string<char>, Oomd::CgroupContext>*, std::vector<std::pair<std::__cxx11::basic_string<char>, Oomd::CgroupContext> > >; _Predicate = Oomd::OomKiller::removeBlacklisted(std::vector<std::pair<std::__cxx11::basic_string<char>, Oomd::CgroupContext> >&)::<lambda(const auto:27&)>]’
  /usr/include/c++/6/bits/stl_algo.h:866:13:   required from ‘_ForwardIterator std::__remove_if(_ForwardIterator, _ForwardIterator, _Predicate) [with _ForwardIterator = __gnu_cxx::__normal_iterator<std::pair<std::__cxx11::basic_string<char>, Oomd::CgroupContext>*, std::vector<std::pair<std::__cxx11::basic_string<char>, Oomd::CgroupContext> > >; _Predicate = __gnu_cxx::__ops::_Iter_pred<Oomd::OomKiller::removeBlacklisted(std::vector<std::pair<std::__cxx11::basic_string<char>, Oomd::CgroupContext> >&)::<lambda(const auto:27&)> >]’
  /usr/include/c++/6/bits/stl_algo.h:936:30:   required from ‘_FIter std::remove_if(_FIter, _FIter, _Predicate) [with _FIter = __gnu_cxx::__normal_iterator<std::pair<std::__cxx11::basic_string<char>, Oomd::CgroupContext>*, std::vector<std::pair<std::__cxx11::basic_string<char>, Oomd::CgroupContext> > >; _Predicate = Oomd::OomKiller::removeBlacklisted(std::vector<std::pair<std::__cxx11::basic_string<char>, Oomd::CgroupContext> >&)::<lambda(const auto:27&)>]’
  ../OomKiller.cpp:238:73:   required from here
  ../OomKiller.cpp:238:72: error: cannot call member function ‘bool Oomd::OomKiller::isBlacklisted(const string&)’ without object
             [this](const auto& pair) { return isBlacklisted(pair.first); }),

This is documented as a GCC bug in https://gcc.gnu.org/bugzilla/show_bug.cgi?id=61636 and https://gcc.gnu.org/bugzilla/show_bug.cgi?id=67274.

Reviewed By: danobi

Differential Revision: D9017746

fbshipit-source-id: 86da97054e53ac467e6bd39c13569837d85a24a3